package main;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JPopupMenu;
import swing.DataSearch;
import swing.PainelBusca;

/**
 * @author Diego Barbosa da Silva
 */
public class Main extends javax.swing.JFrame {

    private JPopupMenu menu;
    private PainelBusca busca;

    public Main() {
        initComponents();
        menu = new JPopupMenu();
        busca = new PainelBusca();
        menu.setBorder(BorderFactory.createLineBorder(new Color(164, 164, 164)));
        menu.add(busca);
        menu.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoBusca = new swing.MyTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoBusca.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/search_1.png"))); // NOI18N
        campoBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoBuscaMouseClicked(evt);
            }
        });
        campoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBuscaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoBuscaMouseClicked
        menu.show(campoBusca, 0, campoBusca.getHeight());
    }//GEN-LAST:event_campoBuscaMouseClicked

    private void campoBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyReleased
        String texto = campoBusca.getText().trim().toLowerCase();
        busca.setData(search(texto));
        if (busca.getItemSize() > 0) {
            // * 2 top and bot border
            menu.show(campoBusca, 0, campoBusca.getHeight());
            menu.setPopupSize(menu.getWidth(), (busca.getItemSize() * 35) + 2);
        } else {
            menu.setVisible(false);
        }
    }//GEN-LAST:event_campoBuscaKeyReleased

    private List<DataSearch> search(String search) {
        int limite = 7;
        List<DataSearch> lista = new ArrayList<>();
        String dataTeste[] = {"Smartphone Samsung Galaxy",
            "Notebook Dell Inspiron",
            "Fone de Ouvido Bluetooth",
            "Smart TV LG 50 polegadas",
            "Tablet Apple iPad",
            "Câmera Digital Canon",
            "Mouse Gamer Logitech",
            "Teclado Mecânico Redragon",
            "Monitor LED Samsung 24 polegadas",
            "Caixa de Som JBL Portátil"};
        for (String d : dataTeste) {
            if (d.toLowerCase().contains(search)) {
                lista.add(new DataSearch(d, false));
                if (lista.size() == limite) {
                    break;
                }
            }
        }

        return lista;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyTextField campoBusca;
    // End of variables declaration//GEN-END:variables
}
