package swing;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @author Diego Barbosa da Silva
 */
public class BuscaItem extends javax.swing.JPanel {
    
    public BuscaItem(DataSearch data) {
        initComponents();
        setData(data);
    }
    
    private void setData(DataSearch data) {
        addEventMouse(this);
        lbTexto.setText(data.getTexto());
        if (data.isStory()) {
            lbTexto.setForeground(new Color(29, 106, 205));
            lbIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/time.png")));
            lbRemover.setCursor(new Cursor(Cursor.HAND_CURSOR));
        } else {
            lbRemover.setText("");
        }
            
    }
    
    /**
     * Método que controla a cor de fundo do item, ao passar o mouse sobre ele.
     * @param com 
     */
    private void addEventMouse(Component com) {
        com.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                setBackground(new Color(215, 216, 216));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setBackground(Color.WHITE);
            }
            
            
            
        });
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIcone = new javax.swing.JLabel();
        lbTexto = new javax.swing.JLabel();
        lbRemover = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 35));

        lbIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/search_small.png"))); // NOI18N

        lbTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTexto.setForeground(new java.awt.Color(48, 48, 48));
        lbTexto.setText("Texto..");

        lbRemover.setForeground(new java.awt.Color(163, 163, 163));
        lbRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRemover.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIcone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addComponent(lbRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIcone;
    private javax.swing.JLabel lbRemover;
    private javax.swing.JLabel lbTexto;
    // End of variables declaration//GEN-END:variables
}
