package swing;

import java.util.List;
import net.miginfocom.swing.MigLayout;

/**
 * @author Diego Barbosa da Silva
 */
public class PainelBusca extends javax.swing.JPanel {

    /**
     * Creates new form PainelBusca
     */
    public PainelBusca() {
        initComponents();
        setLayout(new MigLayout("fillx", "0[]0", "0[]"));
    }
    
    public void setData(List<DataSearch> data) {
        this.removeAll();
        for(DataSearch d:data) {
            BuscaItem item = new BuscaItem(d);
            this.add(item, "wrap");
            // wrap significa adicionar um novo item após esse
            // this for miglayout option
        }
        repaint();
        revalidate();
        // Refresh component
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
